version: '3'
services:
  frontend:
    build:
      context: ./frontend/.
    tty: true
    ports:
      - "3000:3000"
    environment:
     - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app
    command: sh -c "npm run dev"

  backend:
    build: ./backend/.
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
    ports:
      - "4000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
